---
- hosts: all
  become: yes
  tasks:
    - name: Install JDK 11 on CentOS
      yum:
        name: java-11-openjdk-devel
        state: latest
      when: ansible_os_family == "RedHat"

    - name: Install JDK 11 on Debian
      apt:
        name: openjdk-11-jdk
        state: latest
      when: ansible_os_family == "Debian"

    - name: Copy Jar to server
      copy:
        src: ../target/LongArythmeticsJDK11-1.0-SNAPSHOT.jar
        dest: LongArythm.jar
        remote_src: no

    - name: Запуск JAR
      shell: java -jar SmartHome.jar